site_name: LA-CoNGA physics - courses
repo_url: https://github.com/LA-CoNGA-MiLab-RedClara/class-material-mkdocs
# Contents
nav:
    - Inicio: 'index.md'
    - Introducción:
      - La-CoNGA Physics: 'intro/conga.md'
      - The ATLAS Detector: 'intro/experiment.md'
    - Módulo de Teoría:
      - Overview: 'modulo-teoria/intro.md'
    - Módulo de Anánisis de Datos:
      - Overview of physics analysis examples: 'modulo-datos/intro.md'
    - Módulo de Instrumentación:
      - Introduction: 'modulo-instrumentacion/intro.md'
    - Herramientas:
      - Introduction: 'tools/intro.md'
      - Analysis examples: 'tools/notebooks/analysis-examples.md'
      - C++ framework interface: 'tools/notebooks/framework-interface.md'
      - Virtual Machines: 'tools/vm/index.md'
      - VirtualBox installation: 'tools/vm/vb.md'
      - 13 TeV ATLAS Open Data virtual machine installation : 'tools/vm/vm.md'
    - Glosario:
      - Glossary: 'intro/GLOSSARY.md'
# Theme
theme:
  name: null
  custom_dir: 'material'
  language: es
  palette:
    primary: white
    accent: black
  font:
    text: Ubuntu
    code: Roboto Mono
  logo: "images/outline_80_white.png"
  feature:
    tabs: true
  static_templates:
    - 404.html
  favicon: 'assets/images/favicon.ico'
  search_index_only: true
use_directory_urls: false
##
extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
markdown_extensions:
    - toc:
#        toc_depth : "1-1"
        permalink : true
    - mdx_math
